java_test(
  name = "unit_tests",
  size = "small",
  srcs = ["com/redbrick/devchat/rblinks/TestRbLinkBot.java"],
  test_class = "com.redbrick.devchat.rblinks.TestRbLinkBot",
  deps = [
    "//src:rblinkbot",
    "@junit//jar"
  ]
)
