java_import(
  name='mongo-java',
  visibility = ['//visibility:public'],
  jars = [
    'mongo-java-driver-2.11.2.jar'
  ]
)

java_import(
  name = 'pircbot',
  visibility = ['//visibility:public'],
  jars = [
    'pircbot.jar'
  ]
)
